Started to create classes to send workflow configurations to the cloud
php-etl/satellite pull request #133
Opened 2023-10-23 15:25 UTC by sebprt

2023-10-25 10:22 UTC, clemzarch commented on src/Cloud/Console/Command/CreateCommand.php
> +        $this->addArgument('type', Console\Input\InputArgument::REQUIRED, 'Type de configuration (pipeline ou workflow)');
in english pliz

2023-10-25 10:23 UTC, clemzarch commented on src/Cloud/Console/Command/CreateCommand.php
> +            $output->writeln('Le type doit être soit "pipeline" soit "workflow".');
in english

2023-10-26 15:09 UTC, clemzarch commented on src/Cloud/Console/Command/CreateCommand.php
> +            $style->warning('The current version of your configuration does not allow you to use Cloud commands. Please update your configuration to version 0.3.');
on pourrait mettre un lien vers la doc

2023-10-26 15:18 UTC, clemzarch commented on src/Cloud/DTO/PipelineInterface.php
>  }
pas de `$composer` dans cette interface ?

2023-11-21 23:41 UTC, gplanchat approved these changes

2024-01-15 10:42 UTC, gplanchat requested changes

2024-01-15 10:42 UTC, gplanchat commented on src/Builder/API/APIRuntime.php
> +                                                class: new Node\Name\FullyQualified('Ps\\Log\\NullLogger')
```suggestion
                                                class: new Node\Name\FullyQualified('Psr\\Log\\NullLogger')
```

2024-01-15 10:42 UTC, gplanchat commented on src/Cloud/Console/Command/RemoveCommand.php
> +            'php://fd/3',
Pourquoi est-ce que l'option `output` a été retirée ?

2024-01-15 10:42 UTC, gplanchat commented on src/Cloud/Handler/Pipeline/AddBeforePipelineStepCommandHandler.php
> -
Pourquoi est-ce que ce cas a été supprimé ?

2024-01-15 10:42 UTC, gplanchat commented on src/Cloud/Handler/Pipeline/DeclarePipelineCommandHandler.php
> +                                    ->setToken($auth->token)
On a plusieurs types d'authentifications dans l'API. Il faudrait créer un ticket pour répercuter ces types d'authentification dans le client.

2024-01-15 10:42 UTC, gplanchat commented on src/Cloud/Handler/Pipeline/DeclarePipelineCommandHandler.php
> +                                    ->setUrl($repository->url)
On e plusieurs types de dépôts dans l'API. Il faudrait créer un ticket pour répercuter ces types d'authentification dans le client.

2024-01-15 10:42 UTC, gplanchat commented on src/Service.php
> +        foreach ($config['workflow']['jobs'] as $job) {
Il me semble que ça rentre en conflit avec une des dernières PR faites.

2024-01-15 11:09 UTC, sebprt commented on src/Service.php
> +        foreach ($config['workflow']['jobs'] as $job) {
Effectivement, c'est corrigé

2024-01-15 11:13 UTC, sebprt commented on src/Cloud/Console/Command/RemoveCommand.php
> +            'php://fd/3',
Je l'avais supprimé car l'option n'était pas défini dans la méthode `configure` de la classe.

![image](https://github.com/php-etl/satellite/assets/47692802/42603344-2530-4fb1-a780-ad64852f48fe)

Mais du coup je l'ai rajouté

![image](https://github.com/php-etl/satellite/assets/47692802/873f2c68-a7d7-4f01-8666-fec77538a8ad)

2024-01-15 11:19 UTC, sebprt commented on src/Cloud/Handler/Pipeline/AddBeforePipelineStepCommandHandler.php
> -
On avait nul dans le cas où le token JWT n'était pas valide...
Mais ce problème de token a été corrigé en dé-commentant d'autres lignes dans le code.

2024-01-15 13:26 UTC, sebprt commented on src/Cloud/Handler/Pipeline/DeclarePipelineCommandHandler.php
> +                                    ->setUrl($repository->url)
J'ai créé ce ticket du coup : https://github.com/php-etl/satellite/issues/146

2024-01-15 13:26 UTC, sebprt commented on src/Cloud/Handler/Pipeline/DeclarePipelineCommandHandler.php
> +                                    ->setToken($auth->token)
J'ai créé ce ticket du coup : https://github.com/php-etl/satellite/issues/145

2024-01-15 13:31 UTC, gplanchat commented on src/Cloud/Handler/Pipeline/AddBeforePipelineStepCommandHandler.php
> -
Dans ce cas, il faut revoir les paramètres de Jane. Le paramètre `throw-unexpected-status-code` doit être forcé à `true` pour que l'on ait un traitement des cas qui ne seraient pas décrits par la doc.

Exemple :
https://github.com/php-etl/harbor-api-client/blob/main/.jane-openapi#L21

2024-01-17 09:07 UTC, gplanchat requested changes

2024-01-17 09:28 UTC, sebprt commented on src/Cloud/Console/Command/RemoveCommand.php
> +        foreach ($instance->remove($instance::fromApiWithCode($client, array_key_first($configuration['satellites']))->id()) as $command) {
J'ai crée ce ticket : https://github.com/php-etl/satellite/issues/149

2024-01-17 10:19 UTC, gplanchat approved these changes

2024-01-17 10:19 UTC, merged