Added the ability to add code to a job in a workflow
php-etl/satellite pull request #144
Opened 2024-01-10 13:13 UTC by sebprt

```yaml
version: '0.3'
satellites:
  akeneo_to_csv_test:
    label: 'Export into csv'
    filesystem:
      path: build
    workflow:
      name: 'Akeneo to csv'
      jobs:
        - code: 'extract_products_from_akeneo_to_csv' # possibilité d'ajouter un code a un job
          pipeline:
            name: 'Extract products from Akeneo'
```yaml

2024-01-10 13:39 UTC, gplanchat requested changes

2024-01-10 13:39 UTC, gplanchat commented on src/Runtime/Workflow/Configuration.php
> +                            ->end()
Il te manque de mettre cet attribut en clé avec un appel à `useAttributeAsKey` sur l'Array Node.
https://symfony.com/doc/current/components/config/definition.html#array-node-options

2024-01-10 13:41 UTC, gplanchat commented on src/Service.php
> +        foreach ($config['workflow']['jobs'] as $job) {
Avec le `useAttributeAsKey` ce changement sera à annuler.

2024-01-10 16:13 UTC, sebprt commented on src/Service.php
> +        foreach ($config['workflow']['jobs'] as $job) {
Effectivement, j'ai remis comme avant dans cette classe

2024-01-10 16:13 UTC, sebprt commented on src/Runtime/Workflow/Configuration.php
> +                            ->end()
C'est ajouté

2024-01-11 11:25 UTC, gplanchat approved these changes

2024-01-11 11:26 UTC, merged