Fixed the new run command
php-etl/satellite pull request #147
Opened 2024-01-16 08:09 UTC by sebprt

2024-01-16 08:47 UTC, gplanchat requested changes

2024-01-16 08:47 UTC, gplanchat commented on src/Service.php
> +            'symfony/dependency-injection:^6.0',
Ces dépendances ne sont pas toutes justifiées. Cette modification fonctionne exclusivement dans le cas où on compile sur du filesystem.

Je doute que ça puisse fonctionner correctement dans un cas de build Docker ou Cloud. Au mieux, ça ajoute des dépendances qui n'ont pas à être présentes dans ces 2 cas. Ça pourra provoquer des effets de bord lors du build, ou lors de l'exécution.

2024-01-16 09:32 UTC, JoMessina approved these changes

2024-01-16 10:13 UTC, sebprt commented on src/Service.php
> +            'symfony/dependency-injection:^6.0',
J'ai build et exécuter un satellite en utilisant docker et ça fonctionne également.

De plus, actuellement il n'existe rien pour gérer les dépendances en fonction du runtime ?

2024-01-16 10:34 UTC, gplanchat commented on src/Service.php
> +            'symfony/dependency-injection:^6.0',
Le problème n'est pas de savoir si dans ton cas aucune erreur n'apparait. Le problème est d'avoir des dépendances obligatoires qui vont empêcher d'en installer d'autres souhaitées par l'utilisateur ou par le runtime Cloud.

2024-01-17 08:34 UTC, gplanchat approved these changes

2024-01-17 08:35 UTC, gplanchat commented
Il reste 2 points a régler sur cs-fixer https://github.com/php-etl/satellite/actions/runs/7544116483/job/20536686963?pr=147

2024-01-17 11:38 UTC, gplanchat approved these changes

2024-01-17 11:38 UTC, merged