Added state for workflows
php-etl/satellite pull request #29
Opened 2021-09-21 15:39 UTC by sebprt

2021-09-24 14:54 UTC, gplanchat requested changes

2021-09-24 14:54 UTC, gplanchat commented on src/Builder/Pipeline.php
> +    public function getNode(): Node\Stmt
On a une incohérence par rapport à tout le reste de l'application, ça serait le premier builder qui renvoie un `Node\Stmt`

2021-09-24 14:54 UTC, gplanchat commented on src/Builder/Pipeline/ConsoleRuntime.php
> +    public function getNode(): Node\Stmt
Idem, ça serait le premier builder qui renvoie un `Node\Stmt`

2021-09-27 09:10 UTC, sebprt commented on src/Builder/Pipeline.php
> +    public function getNode(): Node\Stmt
J'ai changé les builders, je te laisse regarder le commit [`6f97ce8` (#29)](https://github.com/php-etl/satellite/pull/29/commits/6f97ce83defe734fbd9a787b4165675337d09224)

2021-09-27 09:11 UTC, sebprt commented on src/Builder/Pipeline/ConsoleRuntime.php
> +    public function getNode(): Node\Stmt
J'ai changé les builders, je te laisse regarder le commit [`6f97ce8` (#29)](https://github.com/php-etl/satellite/pull/29/commits/6f97ce83defe734fbd9a787b4165675337d09224)

2021-09-27 12:14 UTC, gplanchat approved these changes

2021-10-01 07:18 UTC, merged