Feature : Import jobs
php-etl/satellite pull request #62
Opened 2022-04-15 08:46 UTC by sebprt

2022-04-20 08:26 UTC, gplanchat requested changes

2022-04-20 08:26 UTC, gplanchat commented on src/ConfigLoader.php
> +                        }
Il faut également faire ne sorte que les chemins soient relatifs au fichier dans lequel l'import est écrit.

2022-04-20 15:30 UTC, sebprt commented on src/ConfigLoader.php
> +                        }
J'ai fait en sorte que les chemins soient relatifs au fichier de base.

2022-04-20 15:37 UTC, gplanchat commented on src/ConfigLoader.php
> +                        }
Il faut qu'ils soient relatifs au fichier dans lequel l'import est écrit

2022-04-20 15:41 UTC, gplanchat commented on src/ConfigLoader.php
> +    {
Il y a un souci dans ta config PHP-CS-Fixer

2022-04-20 15:42 UTC, gplanchat commented on src/ConfigLoader.php
> +            throw new InvalidConfigurationException('Provided configuration seems to be empty, supported formats are YAML and JSON.');
```suggestion
            throw new InvalidConfigurationException('Provided configuration seems to be empty or in an unsupported format. Supported formats are YAML and JSON.');
```

2022-04-20 15:44 UTC, gplanchat commented on src/ConfigLoader.php
> +    {
```suggestion
        string $path,
    ): \Generator {
```

2022-04-20 15:45 UTC, gplanchat approved these changes

2022-04-25 08:31 UTC, gplanchat commented
Il faut corriger les tests PHPUnit

2022-04-27 07:53 UTC, merged