Updated dependencies + used interfaces from php-etl/configurator-cont…
php-etl/satellite pull request #75
Opened 2022-05-30 09:21 UTC by sebprt

…racts

2022-05-30 09:43 UTC, gplanchat commented on src/Adapter/FactoryInterface.php
> -}
On doit ajouter une couche de rétro-compatibilité, comme : https://github.com/php-etl/satellite/blob/main/src/Filesystem/DirectoryInterface.php

2022-05-30 09:44 UTC, gplanchat commented on src/SatelliteInterface.php
> -}
On doit ajouter une couche de rétro-compatibilité, comme : https://github.com/php-etl/satellite/blob/main/src/Filesystem/DirectoryInterface.php

2022-05-30 09:44 UTC, gplanchat commented on src/SatelliteBuilderInterface.php
> -}
On doit ajouter une couche de rétro-compatibilité, comme : https://github.com/php-etl/satellite/blob/main/src/Filesystem/DirectoryInterface.php

2022-05-31 07:26 UTC, sebprt commented on src/SatelliteBuilderInterface.php
> -}
C'est fait.

2022-06-01 14:48 UTC, gplanchat requested changes

2022-06-01 14:48 UTC, gplanchat commented on src/DependencyInjection/Configuration/ServicesConfiguration.php
> +                    foreach ($data as $identifier => $service) {
Pourquoi est-ce que la référence a été retirée ?

2022-06-01 14:48 UTC, gplanchat commented on src/DependencyInjection/Configuration/ServicesConfiguration.php
> +                    foreach ($data as $service) {
Pourquoi est-ce que la référence a été retirée ?

2022-06-01 14:48 UTC, gplanchat commented on src/Plugin/Custom/Configuration/ServicesConfiguration.php
> +                    foreach ($data as $identifier => $service) {
Pourquoi est-ce que la référence a été retirée ?

2022-06-07 08:48 UTC, merged